### ISSUE TITLE
Enable to add?

### ISSUE THREAD

**Issue by JaceRyczak** [puttyman/hass-amplifi#48]
I am using HACS to install this integration. I download it in HACS, then restart as directed. 

I can now find the integration in the "Add Integration" feature in HA. It opens the dialog box that allows me to enter the host and password, but when I click "Submit" it says:

"Enable to connect to amplifi router"
![image](https://github.com/puttyman/hass-amplifi/assets/43364325/f69a3a1d-d480-4157-b0f5-630591c4d3e6)

I can't see any steps that I have missed in the setup instructions, now do I see anywhere I have to "Enable" as it is suggesting.

Can you please let me know what I have missed?

**Comment by hawksj** [comment]
This is the generic error message when it can't connect to the router (admittedly that should be improved...) Have you entered the correct hostname and password for your AmpliFi router? If you didn't change the hostname from "amplifi.lan" then make sure that your HA server actually resolves the hostname amplifi.lan to the IP address of your router. Or just enter the IP address.

Personally I use the IP address as I found it more stable that way than by using the hostname. And of course even if your device is in Bridge mode, make sure it has a static IP address.

**Comment by JaceRyczak** [comment]
Thanks Hawks,

This was the issue, my browser can resolve the hostname, but HA could not apparently. I have an Alien router, and it found most of the devices, but now says the integration is no longer providing info for most of them, must be the limited functionality you mention in your readme! will keep an eye on it....

**Comment by hawksj** [comment]
Thanks for the update @JaceRyczak. I'm not the original creator of this integration but I do help maintain it now. That issue does happen occasionally, I find it happens if you enable an entity which has been disabled by default. To make the entities come back, just restart home assistant after enabling all the entities you want to use and the integration should reload just fine.

There is a pull request to enable devices by default #47. If you want devices to be enabled by default, try cloning the contents of that branch and test using that version. That should do what you're looking for without causing these issues with disabled devices

**Comment by JaceRyczak** [comment]
You are spot on once again, I had just enabled all the default disabled devices. I restarted HA and all is fine now.

Thanks for your help, it is much appreciated!
